version: '2'
services:
    php70cli:
        build: ./php
        ports:
            - "80:80"
        volumes:
            - ../slackReact:/var/www/
        entrypoint:
            - php
            - -S
            - 0.0.0.0:80
            - -t
            - /var/www
